name: Build and test
on: [push, pull_request]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libkqueue-dev
      
      - name: Build using makefile
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: linux-aes-finder
          path: ./bin/aes-finder

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Build using make
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: mac-aes-finder
          path: ./bin/aes-finder

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: |
          msbuild aes-finder.sln /property:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: windows-aes-finder
          path: ./bin/aes-finder.exe